config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # get ':controller(/:action(/:id))'
  root to: 'say#hello'

  use_doorkeeper
  get 'awards/index'
  # root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  concern :voteable do
    member do
      post :create_like
      post :create_dislike
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        post :assigning_as_best
      end
    end

    resources :subscriptions, only: %i[create]
  end

  resources :subscriptions, only: %i[destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[index new edit]
      end
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Voteable
  include Commentable

  scope :for_day, -> { where(created_at: Date.today.all_day) }

  after_create_commit :broadcast_question
  after_create :calculate_reputation
  after_create { subscribe(author) }

  has_many :links, dependent: :delete_all, as: :linkable
  has_many :answers, dependent: :delete_all
  has_many_attached :files
  has_one :award, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :award, reject_if: :all_blank

  belongs_to :author, class_name: 'User'

  validates :title, :body, presence: true

  def broadcast_question
    ActionCable.server.broadcast 'questions', data: self
  end

  def subscribe(user)
    subscriptions.create(user: user) unless subscribed?(user)
  end

  def unsubscribe(user)
    subscriptions.find_by(user: user).destroy if subscribed?(user)
  end

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    @questions = Question.all

    render json: @questions
  end

  def show
    render json: question
  end

  def create
    @question = Question.new(question_params.merge(author: current_resource_owner))

    if @question.save
      render json: @question
    else
      render_json_errors(@question)
    end
  end

  def update
    authorize! :update, question

    if question.update(question_params)
      render json: question
    else
      render_json_errors(@question)
    end
  end

  def destroy
    authorize! :update, question

    question.destroy
  end

  private

  def question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def render_json_errors(resource)
    render json: resource.errors.full_messages, status: :unprocessable_entity
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = question.answers.build
    @answer.links.new
    @question = question
    gon.current_user = current_user
    gon.question = question
    gon.question_id = question.id
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def new
    question.links.build
    question.build_award
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.author = current_user
    if @question.save
      redirect_to @question, notice: "Your question successfully created."
    else
      render :new
    end
  end

  def update
    question.update(question_params) if current_user.author_of?(question)
    flash.now[:notice] = "The question was updated successfully."
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy
      redirect_to questions_path, notice: "Question was successfully deleted"
    else
      redirect_to @question
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body, files: [],
     links_attributes: [:id, :_destroy, :name, :url],
     award_attributes: [:name, :image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_file.html.slim
/вывод тела прикрепленного файла
- if question.files.attached?
  - question.files.each do |file|
    div class="file-#{file.id}"
      p= link_to file.filename.to_s, url_for(file)
      = link_to "Delete this file", attachment_path(file), method: :delete, remote: true

app/views/questions/_form.html.slim
= form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  = f.label :title, 'Your question'
  p= f.text_field :title
  = f.label :body
  p= f.text_area :body
  = f.label :files
  p= f.file_field :files, multiple: true
  h3 Links:
  #tasks
    = f.fields_for :links do |task|
      = render 'links/link_fields', f: task
    .links
        = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
  = f.submit 'Save'
  /вывод тела прикрепленного файла при редактировании вопроса
  div class="file"
    = render "file"

app/views/questions/_question.html.slim
p class="notice"
  = notice
- if question.persisted?
  div class="question-error-#{question.id}"
    = render 'shared/errors', resource: @question
  /вывод тела вопроса
  div class="question-#{question.id}"
    = link_to question.title, question_path(question), class: 'question-title'
    br
    /форма редактирования вопроса
    p = 'Question with the reward!' if question.award.present?
    - if current_user&.author_of?(question)
      = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id }
      = render "form", question: question

app/views/questions/_questions_show.html.slim
p= @question.title
p= @question.body

.comment_errors
  = render 'shared/errors', resource: @comment
= render 'votes/show', resource: @question



- if can?(:create, Comment)
  = link_to 'Add comment', '#', class: 'button-question-comment', data: { question_id: @question.id }
.question-comments
  | Comments:
  = render @question.comments
  = render 'comments/form', commentable: @question

.links
  p Links:
  ul
    -@question.links.each do |link|
      div class="link-id-#{link.id}"
        -if link.to_gist?
          p= render partial: 'links/gist', locals: { link: link }
        -else
          p= link_to link.name, link.url
        - if can?(:destroy, link)
         p= link_to 'Delete link', link_path(link), method: :delete, remote: true


- if @question.files.attached?
  - @question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file)

p = 'Question with the reward!' if question.award.present?

- if can?(:destroy, @question)
  p= link_to 'Delete question', question_path(@question), method: :delete, remote: true

app/views/questions/edit.html.slim
- if can?(:update, Question)
  = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id }
  = render "form", question: question

app/views/questions/index.html.slim
h1 Question Index
- cache collection_cache_key_for :question do
  .question
    = render @questions

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= link_to 'Back to questions', questions_path
/форма создания вопроса
h1 Question New
= form_with model: question, local: true do |f|
  = render 'shared/errors', resource: question
  p
    = f.label :title
    br
    = f.text_field :title
  p
    = f.label :body
    br
    = f.text_area :body
  p
    = f.label :files
    br
    = f.file_field :files, multiple: true
  /вывод формы для создания ссылки относящейся к вопросу
  h3 Links:
  #tasks
  = f.fields_for :links do |task|
    = render 'links/link_fields', f: task
  .links
    = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  h3 Award for the best answer:
  p
    = f.fields_for :award do |a|
      p
        = a.label :name, 'Award name'
        = a.text_field :name
      p
        = a.label :image, 'Award image'
        = a.file_field :image

  p= f.submit 'Create'

app/views/questions/show.html.slim
= link_to 'Back to questions', questions_path

.subscribe
  - if @question.subscribed?(current_user)
    = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, cass: 'unsubscribe-question-link'
  - else
    = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, class: 'subscribe-question-link'

-cache @question do
  h1 Question Show
  .question
    = render 'questions_show', resource: @question

  p Answers:
  .answers
    ol
      = render @question.answers

- if can?(:create, Answer)
  = render template: "answers/new"

app/views/questions/update.js.erb
<% question_error_id = ".question-error-#{@question.id}" %>
$('<%= question_error_id %>').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  <% question_id = ".question-#{@question.id}" %>
  $('<%= question_id %>').replaceWith('<%= j render @question %>');
<% end %>

function clean(){
  $(".notice").empty()
}
setTimeout(clean, 3000);