config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # get ':controller(/:action(/:id))'
  root to: 'say#hello'

  use_doorkeeper
  get 'awards/index'
  # root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  concern :voteable do
    member do
      post :create_like
      post :create_dislike
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        post :assigning_as_best
      end
    end

    resources :subscriptions, only: %i[create]
  end

  resources :subscriptions, only: %i[destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[index new edit]
      end
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  default_scope { order(best: :desc) }

  after_create_commit :broadcast_answer

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'
  has_many_attached :files
  has_many :links, dependent: :delete_all, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  def assign_best
    transaction do
      author.awards << question.award if question.award.present?
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  private

  def broadcast_answer
     ActionCable.server.broadcast "question/#{question.id}/answers", data: answer_data
  end

  def files_data
    data =[]
    files.each do |file|
      data << {
        file_name: file.filename.to_s,
        file_id: file.id,
        file_url: Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true) }
    end

    data
  end

  def links_data
    links_data = []
    links.each { |link| links_data << { link_name: link.name, link_url: link.url } }
    links_data
  end

  def answer_data
    data = {}
    data[:answer] = self
    data[:files] = files_data
    data[:links] = links_data
    data[:vote] = choice

    data
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_answer, only: %i[destroy update assigning_as_best]

  authorize_resource

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    @answer.author = current_user
    flash[:notice] = "Your answer successfully created." if @answer.save
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
    flash[:notice] = "Answer was successfully deleted"
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    flash.now[:notice] = "The answer was updated successfully."
  end

  def assigning_as_best
    @answer.assign_best if current_user.author_of?(@answer.question)
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :_destroy, :name, :url])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def show
    @answer = Answer.find(params[:id])
    render json: @answer
  end

  def create
    @answer = question.answers.new(answer_params.merge(author: current_resource_owner))
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, answer

    if answer.update(answer_params)
      render json: answer
    else
      render_json_errors(@answer)
    end
  end

  def destroy
    authorize! :update, answer
    answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def question
    @question = Question.find(params[:question_id])
  end

  def answer
    @answer = Answer.find(params[:id])
  end

  def render_json_errors(resource)
    render json: resource.errors.full_messages, status: :unprocessable_entity
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api/v1/answers_helper.rb
module Api::V1::AnswersHelper
end

app/views/answers/_answer.html.slim
p class="notice"
  = notice
- if answer.persisted?
  - cache answer do
    div class="answer-#{answer.id}"
      div class="answer-error-#{answer.id}"
        = render 'shared/errors', resource: @answer
      /вывод тела ответа
      li
        = answer.body
        /ресурс для голосования за понравившийся ответ
        = render 'votes/show', resource: answer

        - if can?(:create, Comment)
          = link_to 'Add comment', '#',class: 'button-answer-comment', data: { answer_id: answer.id }
        div class="answer-comments-#{answer.id}"

          | Comments:
          = render answer.comments
          = render 'comments/form', commentable: answer
        /вывод ссылки для ответа
        .links
        p Links:
        ul
          - answer.links.each do |link|
            div class="link-id-#{link.id}"
              -if link.to_gist?
                p= render partial: 'links/gist', locals: { link: link }
              -else
                p= link_to link.name, link.url
              - if can?(:destroy, link)
               p= link_to 'Delete link', link_path(link), method: :delete, remote: true
        / #вывод прикрепленного к ответу файла
        - if answer.files.attached?
          - answer.files.each do |file|
            div class="file-#{file.id}"
              = link_to file.filename.to_s, url_for(file)
              - if can?(:destroy, file)
                = link_to "Delete this file", attachment_path(file), method: :delete, remote: true
            br
        - if answer.best?
          p Best answer of all
        - if can?(:update, answer)
          = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        - if can?(:destroy, answer)
          = link_to 'Delete', answer_path(answer), method: :delete, remote: true
        - if !answer.best? & current_user&.author_of?(answer.question)
          = link_to "Best answer", assigning_as_best_answer_path(answer), method: :post, class: 'best-answer-link', remote: true
        /форма редактирования ответа
        = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, 'Your answer'
          = f.text_area :body
          = f.label :files
          p= f.file_field :files, multiple: true
          p Links:
          #tasks
            = f.fields_for :links do |task|
              = render 'links/link_fields', f: task
            .links
                = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
          = f.submit 'Save'

app/views/answers/_link_fields.slim
.nested-fields
  .field
    = label :name, 'Link name'
    br
    = f.text_field :name, id: "link-name"
  .field
    = f.label :url
    br
    = f.text_field :url

  = link_to_remove_association "remove link", f

app/views/answers/assigning_as_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>')

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer-text').val('');
<% end %>

function clean(){
  $(".answer-errors").empty()
}
setTimeout(clean, 3000);

app/views/answers/delete_attach_file.js.erb
<% file_id = ".file-#{@file.id}" %>
 $('<%= file_id %>').remove();

app/views/answers/destroy.js.erb
 <% answer_id = ".answer-#{@answer.id}" %>
 $('<%= answer_id %>').remove();
 $('.answers').html('<%= notice %>');
function clean(){
  $(".answers").empty()
}
setTimeout(clean, 3000);

app/views/answers/new.html.slim
.form-create-answer
  .answer-errors
    = render 'shared/errors', resource: @answer
  = form_with model: [@question, @answer] do |f|
    = f.label :body, 'Your answer'
    br
    = f.text_area :body
    = f.label :files
    br
    = f.file_field :files, multiple: true
    /вывод вложеной формы создания ссылки принадлежащей ответу
    p Links:
    #tasks
      = f.fields_for :links do |task|
        = render 'links/link_fields', f: task
      .links
        = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
    = f.submit 'Reply'

app/views/answers/update.js.erb
<% answer_error_id = ".answer-error-#{@answer.id}" %>
$('<%= answer_error_id %>').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  <% answer_id = ".answer-#{@answer.id}" %>
  $('<%= answer_id %>').replaceWith('<%= j render @answer %>');
<% end %>

function clean(){
  $(".notice").empty()
}
setTimeout(clean, 3000);