config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # get ':controller(/:action(/:id))'
  root to: 'say#hello'

  use_doorkeeper
  get 'awards/index'
  # root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  concern :voteable do
    member do
      post :create_like
      post :create_dislike
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        post :assigning_as_best
      end
    end

    resources :subscriptions, only: %i[create]
  end

  resources :subscriptions, only: %i[destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[index new edit]
      end
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_authorization_check

  def index
    @searched = Services::Search.search_by(params[:query], params[:type])
  end
end

app/views/searches/_answer.html.slim
p
  ' Answer body:
  = link_to answer.body, question_path(answer.question)
  p
    ' Answer author
    = answer.author.email

app/views/searches/_comment.html.slim
p
  ' Comment body:
  = comment.body
  p
    ' Comment author
    = comment.user.email

app/views/searches/_form.html.slim
.search
  = form_tag search_path, method: :get do
    = select_tag :type,
          options_for_select(Services::Search::TYPES, params[:type]),
          include_blank: 'Global search'
    = text_field_tag :query,
          params[:query]
    = submit_tag 'Search'

app/views/searches/_question.html.slim
p
  ' Question title
  = link_to question.title, question_path(question)
  p
    ' Question body:
    = question.body
    p
      ' Question author
      = question.author.email

app/views/searches/_user.html.slim
p
  ' User email
  = user.email

app/views/searches/index.html.slim
-if @searched.any?
  -@searched.each do |object|
    = render partial: "#{object.class.name.downcase}", object: object
-else
  |No results.