config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # get ':controller(/:action(/:id))'
  root to: 'say#hello'

  use_doorkeeper
  get 'awards/index'
  # root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  concern :voteable do
    member do
      post :create_like
      post :create_dislike
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    resources :answers, shallow: true, only: %i[create update destroy], concerns: [:voteable, :commentable] do
      member do
        post :assigning_as_best
      end
    end

    resources :subscriptions, only: %i[create]
  end

  resources :subscriptions, only: %i[destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[index new edit]
      end
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    link rel="icon" href="/favicon.ico" type="image/x-icon" /
    link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /
    title Think
    = Gon::Base.render_data
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      - if user_signed_in?
        = link_to current_user.email
        br
        = link_to 'Awards', awards_path
        br
        = link_to 'Log out', destroy_user_session_path, method: :delete
      - elsif !current_page?(new_user_session_path)
        = link_to 'Log in', new_user_session_path
      = render 'searches/form'
    main
      p.notice= notice
      p.alert= alert
      .content
        = yield